#!/usr/bin/env bash
# init.sh — Initialize or upgrade the Planner-Executor workflow.
#
# Usage:
#   ./scripts/init.sh             Full init (first time)
#   ./scripts/init.sh --upgrade   Re-run detection, update scripts only
#                                 (preserves CLAUDE.md, copilot-instructions.md, config.yaml)

set -euo pipefail

UPGRADE=false
if [[ "${1:-}" == "--upgrade" ]]; then
    UPGRADE=true
fi

CONFIG_FILE=".planner-executor/config.yaml"
CONFIG_TEMPLATE=".planner-executor/config.yaml.template"

# ── Step 1: Detect project type ───────────────────────────────────────────────
echo "→ Detecting project type..."
# shellcheck source=detect-project.sh
source "$(dirname "$0")/detect-project.sh" 2>/dev/null || true

echo "  Type:  ${DETECTED_TYPE:-unknown}"
echo "  Build: ${DETECTED_BUILD:-[not detected]}"
echo "  Test:  ${DETECTED_TEST:-[none]}"
echo "  Run:   ${DETECTED_RUN:-[none]}"

# ── Step 2: Write config.yaml ─────────────────────────────────────────────────
mkdir -p .planner-executor

if [[ ! -f "$CONFIG_FILE" || "$UPGRADE" == "true" ]]; then
    echo "→ Writing $CONFIG_FILE ..."
    cat > "$CONFIG_FILE" <<YAML
# .planner-executor/config.yaml
# Generated by scripts/init.sh — edit freely after generation.

project_name: "AppBookingResPi4"
project_type: "${DETECTED_TYPE:-c-make}"

build_cmd: "${DETECTED_BUILD:-make clean && make}"
test_cmd:  "${DETECTED_TEST:-}"
lint_cmd:  "${DETECTED_LINT:-}"
run_cmd:   "${DETECTED_RUN:-./appbooking -p 8080 -d /tmp/test.db}"

plans_dir: ".plans"
executor:  "copilot"
max_retries: 0

env_setup: ""
YAML
    echo "  Written: $CONFIG_FILE"
else
    echo "  Skipping $CONFIG_FILE (already exists — use --upgrade to refresh)"
fi

# ── Step 3: Ensure directories exist ─────────────────────────────────────────
mkdir -p .plans skills .claude .github

# ── Step 4: Create skills manifest if missing ─────────────────────────────────
if [[ ! -f "skills/manifest.json" ]]; then
    echo "→ Generating skills/manifest.json ..."
    ./scripts/update-manifest.sh
fi

# ── Step 5: Make all scripts executable ──────────────────────────────────────
chmod +x scripts/*.sh
echo "→ Scripts marked executable."

# ── Step 6: VS Code settings ──────────────────────────────────────────────────
VSCODE_SETTINGS=".vscode/settings.json"
if [[ ! -f "$VSCODE_SETTINGS" ]]; then
    mkdir -p .vscode
    cat > "$VSCODE_SETTINGS" <<'JSON'
{
  "github.copilot.chat.useInstructionFiles": true
}
JSON
    echo "→ Written: $VSCODE_SETTINGS (enables Copilot instruction files)"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "Setup complete."
echo ""
echo "Next steps:"
echo "  1. Review .planner-executor/config.yaml — correct any commands"
echo "  2. Open VS Code: code ."
echo "  3. Ask Claude to create a plan: './scripts/plan-executor.sh new <feature>'"
echo "  4. Ask Copilot: 'Implement the plan from .plans/YYYY-MM-DD-<feature>/'"
echo ""
echo "Available commands:"
echo "  ./scripts/plan-executor.sh list              — list all plans"
echo "  ./scripts/plan-executor.sh new <name>        — scaffold a plan"
echo "  ./scripts/plan-executor.sh status <folder>   — show task progress"
echo "  ./scripts/plan-executor.sh open <folder>     — print plan for Copilot"
echo "  ./scripts/plan-executor.sh test              — run build+test from config"
echo "  ./scripts/load_skill.sh list                 — list available skills"
