# Source with: source /home/phuong/robot_voice/quick_commands.sh
alias proj='cd /home/phuong/robot_voice'
alias src='cd /home/phuong/robot_voice/src'
alias logs='cd /home/phuong/robot_voice/logs'
alias test='cd /home/phuong/robot_voice/tests'
alias setup_i2s='sudo bash /home/phuong/robot_voice/scripts/setup_i2s.sh'
alias install_deps='bash /home/phuong/robot_voice/scripts/install_deps.sh'
alias test_hw='python /home/phuong/robot_voice/scripts/test_i2s.py'
alias run='python /home/phuong/robot_voice/src/main.py'
alias run_dry='ROBOT_DRY_RUN=1 python /home/phuong/robot_voice/src/main.py'
alias run_debug='python /home/phuong/robot_voice/src/main.py --debug'
alias test_all='pytest /home/phuong/robot_voice/tests/ -v'
alias test_unit='pytest /home/phuong/robot_voice/tests/unit/ -v'
alias test_int='pytest /home/phuong/robot_voice/tests/integration/ -v'
alias start_robot='sudo systemctl start robot-voice'
alias stop_robot='sudo systemctl stop robot-voice'
alias restart_robot='sudo systemctl restart robot-voice'
alias status_robot='sudo systemctl status robot-voice'
alias logs_robot='sudo journalctl -u robot-voice -f'
alias check_mic='arecord -D hw:0,0 -f S16_LE -r 16000 -c 1 -d 3 /tmp/test.wav && aplay /tmp/test.wav'
alias check_speaker='speaker-test -D hw:0,0 -c 1 -t sine -f 1000'
alias check_devices='python -c "import pyaudio; p = pyaudio.PyAudio(); [print(p.get_device_info_by_index(i)) for i in range(p.get_device_count())]"'
alias check_i2s='dmesg | grep -E "i2s|dmic|max98357"'
alias check_gpio='raspi-gpio get 18,19,20,21'
alias check_pins='gpio readall'
